Ajout du message de prévention sur les fichiers qml
IGNF/cartes.gouv.fr pull request #574
Opened 2024-12-02 15:56 UTC by cbrousseau1

2024-12-03 14:19 UTC, slafayIGN requested changes
Je me suis permis de modifier le titre et la description de la PR. N'hésite pas à écrire des choses dans la description et surtout à faire le lien avec l'issue s'il y en a une (il suffit d'écrire `#numero` et git fait le lien tout seul).

Dans ce dépôt on utilise des messages de commit qui suivent le pattern "conventional commit" (https://www.conventionalcommits.org/en/v1.0.0/). D'où mon préfixage du message par `feat(style):`.

`package-lock.json` ne doit PAS faire partie de cette PR. Cette modification ne justifie pas une mise à jour des dépendances.

2024-12-03 14:19 UTC, slafayIGN commented on assets/entrepot/pages/service/view/Style/UploadLayerStyles.tsx
> +                    <div className="fr-alert fr-alert--warning">{t("qml_message")}</div>
Utilise plutôt le composant Alert : https://components.react-dsfr.codegouv.studio/?path=/docs/components-alert--default

2024-12-03 15:13 UTC, slafayIGN commented on assets/entrepot/pages/service/view/Style/UploadLayerStyles.tsx
> +                    <br />
Plutôt qu'un ligne vide, utilise une classe du DSFR sur le composant Alert.

Par exemple : `className={fr.cx("fr-mb-3v")}`

2024-12-03 15:49 UTC, slafayIGN approved these changes

2024-12-03 15:51 UTC, merged

2025-01-02 11:32 UTC, IGNF-Xavier commented
![image](https://github.com/user-attachments/assets/6229d057-40b0-433a-9459-70078c7a1b05)