fix: dépôt vecteur - échec à la vérification standard et vecteur #579
IGNF/cartes.gouv.fr pull request #606
Opened 2024-12-20 16:21 UTC by cbrousseau1

contient les issues #582, #583, #584, #585 et #588.

2025-01-06 15:12 UTC, slafayIGN requested changes
Sur la forme je pense qu'il est préférable de coller au vocabulaire de l'API et utiliser `Upload` plutôt que `Delivery`. Le terme `Delivery` n'est d'ailleurs pas présent dans la base de code avant cette PR.

Pourrait-tu renommer les composants, méthodes et fichiers concernés ?

Et en termes d'organisation, je trouve qu'il y a beaucoup de choses dans `assets/entrepot/pages/stored_data/StoredDataDetails` dont la moitié concerne les détails d'un `Upload`. Il vaudrait peut-être mieux réorganiser en un dossier `assets/pages/details/` avec des sous-dossiers `stored_data` et `upload`. @ocruze tu as un avis ?

Enfin voyez ensemble pour résoudre les conflits avec la branche `main`.

2025-01-06 15:12 UTC, slafayIGN commented on assets/@types/app.ts
> +export type DeliveryReport = {
Dans le vocabulaire entrepôt on parle d'`Upload` pour les livraisons. Renomme plutôt en UploadReport.

2025-01-06 15:12 UTC, slafayIGN commented on assets/entrepot/pages/datasheet/DatasheetView/DatasetListTab/UnfinishedUploadList.tsx
> +                            <h6 className={fr.cx("fr-m-0")}>{t("storage.upload.deletion.in_progress")}</h6>
Est-ce que ce niveau hiérarchique (`<h6>`) est sûr ?
Même si l'affichage est temporaire le temps de la suppression, il faut veiller à ne pas faire des trous dans la hiérarchie. Un simple paragraphe pourrait suffire non ?

2025-01-06 15:12 UTC, slafayIGN commented on assets/entrepot/pages/stored_data/StoredDataDetails/DeliveryDetails.tsx
L'emplacement et le nommage ne sont peut-être pas idéal. Un pages/upload/UploadDetails collerait davantage à l'API.

2025-01-06 15:58 UTC, ocruze commented
Je suis d'accord pour renommer Delivery en Upload.

Pour la réorganisation de fichiers, je pense qu'il n'y pas assez de fichiers différents pour stored_data et upload pour faire des sous-dossiers. Seulement les composants PreviewTab et StoredDataDetails ont 2 composants séparés, les autres composants (tout ce qui est dans ReportTab) sont communs. 

Ce que je propose, c'est d'avoir comme dossier principal `assets/entrepot/pages/data_details` (`data_details` parce que stored_data et upload ce sont 2 types de données). Ensuite,
- PreviewTab/UploadPreviewTab
- PreviewTab/StoredDataPreviewTab
- UploadDetails
- StoredDataDetails

2025-01-06 16:02 UTC, ocruze commented on assets/entrepot/pages/datasheet/DatasheetView/DatasetListTab/UnfinishedUploadList.tsx
> +                            <h6 className={fr.cx("fr-m-0")}>{t("storage.upload.deletion.in_progress")}</h6>
Le `<h6>` fait partie du code existant. Je veux dire c'est dans un bloc de code utilisé à beaucoup d'endroits sur le site. Si on veut le modifier, il faudra modifier partout. 
J'avais mis un h au lieu de p parce que c'est le titre du contenu de la modale

2025-01-07 14:16 UTC, ocruze commented on assets/modules/entrepot/RQKeys.ts
> +    datastore_upload_report: (datastoreId: string, uploadDataId: string): string[] => ["datastore", datastoreId, "upload_data", uploadDataId, "report"],
```suggestion
    datastore_upload_report: (datastoreId: string, uploadId: string): string[] => ["datastore", datastoreId, "upload", uploadId, "report"],
```
Je conseille de garder l'homogénéité parce que ça aide à react-query de grouper des requêtes

2025-01-07 14:17 UTC, ocruze commented on assets/router/RouterRenderer.tsx
> +const UploadReport = lazy(() => import("../entrepot/pages/data_details/UploadDetails"));
```suggestion
const UploadDetails = lazy(() => import("../entrepot/pages/data_details/UploadDetails"));
```

2025-01-07 14:18 UTC, ocruze commented on assets/router/RouterRenderer.tsx
> +                return <UploadReport datastoreId={route.params.datastoreId} uploadDataId={route.params.uploadDataId} />;
```suggestion
                return <UploadDetails datastoreId={route.params.datastoreId} uploadDataId={route.params.uploadDataId} />;
```

2025-01-08 14:12 UTC, ocruze approved these changes

2025-01-08 14:23 UTC, slafayIGN approved these changes

2025-01-08 14:27 UTC, merged